clean:
	rm data/*
	rm datasmall/*
	rm -rf SystemC/*

f0:
	../../bin/ArchExp 2G_spec 2G_complib_64 2G_taskgraph 2G_control_f0
f1:
	../../bin/ArchExp 2G_spec 2G_complib_64 2G_taskgraph 2G_control_f1
dall:
	../../bin/ArchExp 2G_spec 2G_complib_dall 2G_taskgraph 2G_control_f0
d120:
	../../bin/ArchExp 2G_spec 2G_complib_120 2G_taskgraph 2G_control_f0
d64:
	../../bin/ArchExp 2G_spec 2G_complib_64 2G_taskgraph 2G_control_f0
d32:
	../../bin/ArchExp 2G_spec 2G_complib_32 2G_taskgraph 2G_control_f0
d16:
	../../bin/ArchExp 2G_spec 2G_complib_16 2G_taskgraph 2G_control_f0
d8:
	../../bin/ArchExp 2G_spec 2G_complib_8 2G_taskgraph 2G_control_f0
p10:
	../../bin/ArchExp 2G_spec 2G_complib_64 2G_taskgraph 2G_control_p10
p50:
	../../bin/ArchExp 2G_spec 2G_complib_64 2G_taskgraph 2G_control_p50
p100:
	../../bin/ArchExp 2G_spec 2G_complib_64 2G_taskgraph 2G_control_p100
